### ISSUE TITLE
Unmatched < meant as Literal < Breaks Highlighting When inline HTML is Present

### ISSUE THREAD

**Issue by Draco18s** [jbt/markdown-editor#101]
For example:

    |        Thing 1       |      Description      |
    |----------------------|-----------------------|
    | HTML | First some html.<ul><li>One</li><li>Twp</li></ul> |
    | `<` | Don't do this, everything goes to hell |
    | Other line | RED MODE ACTIVATED |
    | `'` | No more red |

As it appears in the editor:
![image](https://user-images.githubusercontent.com/1750680/51127043-30cc6b00-17ea-11e9-8167-a16a5ce499dc.png)

[Editable version](https://jbt.github.io/markdown-editor/#dY7NCsIwEITvPsXcvNgW76FQrKJgLUjw5KGgSxNIE0lWRejDm/4cdS87u8s3Oz3mkkrbFut56qdWUrh5/WDt7Lxf9MnP+rNOIoC9rI7Rcad9YATXERR3JhVPkwuj89qSyGIftHw/Jp3F4/ANzVU0ES6dXTLuDqx0WIFe5D88Rm4dBbCDImNGomZFHkZbitx5W6Kqyy2KjTxcChnH0TUfTE8OnfMET/cUB16GmHGgvg==)

Note that the `<` cannot be replaced with `&lt;` as that displays as a literal `&lt;` and it's the single quotes in the text description that gets the red treatment, which will continue until either another `'` is found (anywhere) or the end of the file is reached. Nor can the `'` or `'<` be escaped (e.g. `\'` or `\<`).

This makes it particularly frustrating to edit the markdown page for a custom esolang where `<` one command *and* I require a bulleted list in the description for another command (as it does multiple things, based on its inputs) *and* the syntax highlighting in this case makes the text under it nearly impossible to read.

**Comment by aero31aero** [comment]
The simplest solution could be a mode where you can disable warnings and
such highlights. Fixing the syntax highlighting would require diving into
the source of codemirror or updating codemirror and seeing if the latest
version has fixed it.

Unfortunately I don't have time these days for making a detailed fix, but a
disable-warnings mode or subtler warning CSS is on the way.

**Comment by cmnguyen01** [comment]
so what would you recommend to add in the codemirror files to implement the changes? I created the disable warning button but would like to know the functionality so I can attempt this issue.

**Comment by aero31aero** [comment]
Hey, I noticed you closed your PR so I pushed a minor fix here. I'd be happy to review any further changes you have in mind for this.

**Comment by Draco18s** [comment]
The live version hasn't updated yet (probably github's caching) but injecting the change at least lets me *read* the text in those regions.
![image](https://user-images.githubusercontent.com/1750680/67621086-cdd51f00-f7d2-11e9-979d-d2df87c4bb56.png)
So, that's fine for now.

**Comment by aero31aero** [comment]
Yeah, I haven't deployed the changes yet. It should be live soon.
