### ISSUE TITLE
[Solved] Not working in Firefox due to charset

### ISSUE THREAD

**Issue by github-young** [jbt/markdown-editor#119]
It cannot work normally in Firefox 75.0. But Chrome is OK.
It turns out that the absence of
```html
<head>
...
<meta charset="UTF-8">
...
</head>
```
causes this.

Simply adding this line solves this problem.

**Comment by aero31aero** [comment]
Hey, it works properly for me in FF75, but I think being explicit here is a good idea. Do you think you could make a PR for this change? I'm very happy to merge one.

Thanks for the report.

**Comment by github-young** [comment]
> 
> 
> Hey, it works properly for me in FF75, but I think being explicit here is a good idea. Do you think you could make a PR for this change? I'm very happy to merge one.
> 
> Thanks for the report.

Thank you. I have made a PR.
