### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by mada0007** [jbt/markdown-editor#126]
Hello Bro I need some help,

Can you please help?

**Comment by aero31aero** [comment]
Hey, we can try to help! Can you elaborate what are you struggling with?

**Comment by mada0007** [comment]
Can you please provide me with your email address so I can message you? 

Thanks very much indeed.

**Comment by aero31aero** [comment]
I'm sorry, I'd prefer to talk on the issue tracker. Can you please describe your issue?

**Comment by mada0007** [comment]
Oh okay sorry I had already sent you an email. But I needed to complete a task on deploying wordpress on on aws and was wonderiing if you could help

**Comment by aero31aero** [comment]
Sorry mate, I can't help you out. Also, this isn't the best place for such a conversation, this issue tracker is meant solely for issues related to the markdown-editor project.

I'll be closing this issue now. Hope you get the job you're applying for with your own efforts. Best of luck!
