### ISSUE TITLE
Blockquote highlighting overflows

### ISSUE THREAD

**Issue by anubiann00b** [jbt/markdown-editor#17]
If you make a blockquote, the blockquote is highlighted in green, but the highlighting overflows to anything after the blockquote.

![image](https://cloud.githubusercontent.com/assets/5544386/4081457/e9817ba4-2ee7-11e4-93c2-7a5b5806c421.png)

**Comment by jbrooksuk** [comment]
This can now be marked as closed @jbt.

https://cldup.com/fKYwJ9fjXY.png

**Comment by jbt** [comment]
Oh yah I remember that sorted itself with the updates to CodeMirror, completely forgot to close this, thanks!
