### ISSUE TITLE
Inside a table, backticked pipe character is not ignored 

### ISSUE THREAD

**Issue by josdejong** [jbt/markdown-editor#20]
Thanks for this great, simple editor. 

I encountered a small bug: Try the following markdown code in the editor:

```md
# Operators

Operator | Description
-------- | -----------
`&`      | Bitwise and
`|`      | Bitwise or
`^`      | Bitwise xor
```

In this table, the line line with "bitwise or" is wrongly parsed as having three columns: The pipe character inside backticks `|` is not ignored but interpreted as a column separator.

**Comment by jbt** [comment]
It looks like this is an issue with [marked](https://github.com/chjj/marked), the markdown parser this project uses internally. I'm actually planning on swapping marked out for [markdown-it](https://github.com/markdown-it/markdown-it) at some point, which is much better-maintained and should improve some of the weirder parsing quirks. However, it looks like [it exhibits the same issue](https://markdown-it.github.io/#md64=eyJzb3VyY2UiOiIjIE9wZXJhdG9yc1xuXG5PcGVyYXRvciB8IERlc2NyaXB0aW9uXG4tLS0tLS0tLSB8IC0tLS0tLS0tLS0tXG5gJmAgICAgICB8IEJpdHdpc2UgYW5kXG5gfGAgICAgICB8IEJpdHdpc2Ugb3JcbmBeYCAgICAgIHwgQml0d2lzZSB4b3IiLCJkZWZhdWx0cyI6eyJodG1sIjpmYWxzZSwieGh0bWxPdXQiOmZhbHNlLCJicmVha3MiOmZhbHNlLCJsYW5nUHJlZml4IjoibGFuZ3VhZ2UtIiwibGlua2lmeSI6dHJ1ZSwidHlwb2dyYXBoZXIiOnRydWUsIl9oaWdobGlnaHQiOnRydWUsIl9zdHJpY3QiOmZhbHNlLCJfdmlldyI6Imh0bWwifX0=) - I have to say I'm not completely familiar with the precedence rules in markdown but if both parsers treat it the same then it may be possible that that's the correct behaviour. I'll dig deeper and see what it's supposed to do.

**Comment by josdejong** [comment]
Thanks!

**Comment by jbrooksuk** [comment]
FWIW this issue isn't fixed by the change to markdown-it.

**Comment by josdejong** [comment]
Hm. Too bad. Is it a known issue at `markdown-it`?

**Comment by jbrooksuk** [comment]
Without backticks it works with a single `\` escape character:

```markdown
# Operators

Operator | Description
-------- | -----------
`&`      | Bitwise and
\|    | Bitwise or
`^`      | Bitwise xor
```

**Comment by josdejong** [comment]
As a workaround I just write it as HTML:

```md
# Operators

Operator | Description
-------- | -----------
`&`      | Bitwise and
<code>&#124;</code> | Bitwise or
`^`      | Bitwise xor
```

**Comment by jbrooksuk** [comment]
For me this returns:

https://cloudup.com/cV8r0FYBHaT

**Comment by jbt** [comment]
Yeah I've been trying to read around this and I can't quite figure out what the desired behaviour should be - best I can find is in [GitHub's GFM description](https://help.github.com/articles/github-flavored-markdown/#tables) but that's annoyingly light on the detail of what kind of precedence order there should be.

It's kind of odd that both marked and markdown-it treat the `|` as higher-precedence than the backticks but GitHub doesn't.

**Comment by jbt** [comment]
This is the corresponding issue in marked btw: https://github.com/chjj/marked/issues/285

Not sure if there's something over on markdown-it, if not I might open one

**Comment by jbt** [comment]
Righty my [PR over on markdown-it](https://github.com/markdown-it/markdown-it/pull/87) is merged now so this should just be a matter of bumping markdown-it and it'll suddenly start working. I'll get that done sometime today

**Comment by josdejong** [comment]
Nice, thanks!

**Comment by jbt** [comment]
Updated and it looks like it works, hurrah!

http://jbt.github.io/markdown-editor/#8y9ILUosyS9SqFFwSS1OLsosKMnMz+PShQKgsC4CcCWoJSiAQY2CU2ZJeWZxqkJiXgpXQg2GcH4RV0IchmhFfhEA

**Comment by josdejong** [comment]
Thanks again! It's these little details that make or brake an app :)
