### ISSUE TITLE
Inline style attribute rendered correctly but not in GitHub

### ISSUE THREAD

**Issue by Vdragon** [jbt/markdown-editor#24]
GitHub sanitizes all inline style attributes but it still renders correctly in Markdown Editor, not sure if it's really a issue of this project since I really like it that way :-)

**Comment by jbt** [comment]
My personal feeling on this is that it's not an issue in the scope of this project. GitHub themselves pass markdown through quite a complicated HTML sanitization pipeline (and remove `<script>` tags for example), whereas the idea of this project is to just be a straight pass-through markdown parser (and the actual markdown spec doesn't include any HTML sanitization or anything). Would you be ok if I closed this then?

**Comment by Vdragon** [comment]
I'm fine with that.
