### ISSUE TITLE
Add option to close "Save" block

### ISSUE THREAD

**Issue by smithtrenton** [jbt/markdown-editor#27]
If you hit ctrl+s but don't want to save, its impossible to close the save dialog that opened. Adding a simple close button would solve this issue(maybe add the hotkey of pressing esc to close it as well).

**Comment by jbt** [comment]
Oops sorry slow reply on this. Totally agree, what's in there at the moment is there mostly because it's better than nothing. Since merging #10 I've wanted to betterize the whole save thing quite a bit because I've got some ideas how to make it much nicer. I'll see what I can do today on it
