### ISSUE TITLE
HTML tags are not rendered

### ISSUE THREAD

**Issue by farin** [jbt/markdown-editor#32]
instead they are escaped. But Github Flavoured markdown permits direct use of HTML.
Simple example is classic <br> tag.

**Comment by jbt** [comment]
Oh good spot. This'll have change when I switched from marked to markdown-it as the renderer, because markdown-it's default is to escape all HTML.

**Comment by jbt** [comment]
There we go, should work properly now

**Comment by farin** [comment]
wow, that was quick. thx now it's perfect,
