### ISSUE TITLE
issue: this is awesome

### ISSUE THREAD

**Issue by vincentwoo** [jbt/markdown-editor#36]
didn't realize you could build this kind of functionality so easily on top of CM. great work, you rule.

**Comment by thorsummoner** [comment]
This ... doesn't constitute an issue. Or if it does, could you please reword your issue into a [user story](https://en.wikipedia.org/wiki/User_story)? Also `CM` is not a reference I've ever herd of, so please expand its acronym, or link in something for reference.

**Comment by vincentwoo** [comment]
![this guy](http://media.giphy.com/media/usUm1EU5N5CBG/giphy.gif)

**Comment by thorsummoner** [comment]
srs pony is srs bsns
I'm sure there original author appreciates your praise ^w^

**Comment by jbt** [comment]
I sure do, thanks @vincentwoo - always great to know stuff is appreciated! :)

btw @thorsummoner `CM` = CodeMirror

**Comment by thorsummoner** [comment]
Thanks!
