### ISSUE TITLE
Consider using CodeMirror.runmode for highlighting?

### ISSUE THREAD

**Issue by vincentwoo** [jbt/markdown-editor#37]
If you're interested in cutting another dependency, you can use something like:

```js
function highlight(code, lang) {
    var dummy = document.createElement('div');
    CodeMirror.runMode(code, lang, dummy);
    return dummy.innerHTML;
}
```

to perform highlighting instead of hljs. You do have to include all the relevant modes, though.

This has the added benefit of making sure the preview highlighting is identical to the output highlighting.

**Comment by jbt** [comment]
This is definitely something I've considered - having consistent highlighting on both input and output is something I'd very much like to have.

As it happens, though, the way I'm currently thinking of tackling that is to go in completely the opposite direction (sorry) and strip out CodeMirror entirely, and using [prism](https://github.com/PrismJS/prism) for highlighting in both input and output. Current status is over on #25. Still definitely not final though

**Comment by vincentwoo** [comment]
I eagerly await your progress - I'm independently building out some of these features in CM land, and it's going... passably.
