### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by kunalsinghal** [jbt/markdown-editor#38]
Hi, 
Awesome editor. Just love the feel of it. But, can we have spell check in the editor? That's one thing that's quite important I believe. 

Thanks!

**Comment by Linkviii** [comment]
Quite important. I shouldn't need to paste into twitter to spell check. What prevents browser spellcheck from working?

**Comment by jakob-stoeck** [comment]
Since the editor is based on CodeMirror its plugins should work. Have you tried https://github.com/NextStepWebs/codemirror-spell-checker?

**Comment by ngtrian** [comment]
how to disable spell check?

**Comment by aero31aero** [comment]
@ngtrian sorry there's no option for that as of now. I'm open to accepting PRs to add a button for that behavior, however.

Also, closing this since we now have spellcheck in the editor.
