### ISSUE TITLE
URL autolinking

### ISSUE THREAD

**Issue by per1234** [jbt/markdown-editor#40]
markdown-editor does not do URL autolinking as [GitHub Flavored Markdown does](https://help.github.com/articles/github-flavored-markdown/).

Very useful project, thank you!

**Comment by jbt** [comment]
Oh good spot, I must've forgotten to enable the `linkify` option when switching to markdown-it. Fix coming right up

**Comment by jbt** [comment]
There we go, should be behaving itself now :)
