### ISSUE TITLE
Use of <br/> within the editor messes up syntax highlighting 

### ISSUE THREAD

**Issue by iamjasonp** [jbt/markdown-editor#43]
Repro:
1. Create a new document using the markdown-editor
2. Insert `<br/>` somewhere in the document editor

Expected: 
* Syntax highlighting continues to work in the editor

Actual: 
* Syntax highlighting does not work after `<br/>

Note that this does not affect the rendering, just the syntax highlighting. 

Thanks!

**Comment by jakob-stoeck** [comment]
In fact any HTML code breaks the syntax highlighting. The CodeMirror markdown mode works, though: https://codemirror.net/mode/markdown/

**Comment by iamjasonp** [comment]
Closing as dupe of #39.
