### ISSUE TITLE
broken table markdown is rendered 'correctly' but not on github

### ISSUE THREAD

**Issue by jethroo** [jbt/markdown-editor#6]
first let me thank you for this nice editor! ;)  

i just stumbled over a maybe not intended behaviour:

```
Item (unrounded)| Price (unrounded) | LareRound | Financial
 --- | --- | --- 
 item | 10.000 | 10.00 | 10.00
 tax  | 0.823  | 0.82  | 0.83
 **Total** | **10.823** | **10.82** | **10.83**
 ```

was rendered as 'correctly' as table in the editor although it was broken, should have been:

```
Item (unrounded)| Price (unrounded) | LareRound | Financial
 --- | --- | --- | ---
 item | 10.000 | 10.00 | 10.00
 tax  | 0.823  | 0.82  | 0.83
 **Total** | **10.823** | **10.82** | **10.83**
 ```

difference of both can be tested right in this comment:

Item (unrounded)| Price (unrounded) | LareRound | Financial
 --- | --- | --- 
 item | 10.000 | 10.00 | 10.00
 tax  | 0.823  | 0.82  | 0.83
 **Total** | **10.823** | **10.82** | **10.83**

Item (unrounded)| Price (unrounded) | LareRound | Financial
 --- | --- | --- | ---
 item | 10.000 | 10.00 | 10.00
 tax  | 0.823  | 0.82  | 0.83
 **Total** | **10.823** | **10.82** | **10.83**

sincerely yours 

Carsten

**Comment by jbt** [comment]
Oops, sorry for lack of response on this. This is indeed an issue with marked, the rendering engine. I'm currently working on the possibility of switching to [markdown-it](https://github.com/markdown-it/markdown-it) as it's a lot better maintained and more pluggable, and it handles this case correctly
