### ISSUE TITLE
Stagnation

### ISSUE THREAD

**Issue by aero31aero** [jbt/markdown-editor#61]
There have been 6 PRs that haven't been gotten around to. Since your project gets the highest hits on the internet, it doesn't make sense to fork it and start over on a 'new' url. I would like you to consider adding more maintainers to the project.

Regards
Rohitt

**Comment by smileytechguy** [comment]
ill maintain

**Comment by aero31aero** [comment]
I've fixed around 5-6 more issues as well as added significant number of features to my fork that I would like to merge to this. @jbt it seems you are busy with other projects and I am relatively free this year so I can take up the job of maintaining the code. Please respond.

**Comment by jbt** [comment]
You're absolutely right, I've done a pretty awful job here. I've been meaning to open a call-for-maintainers for a couple of weeks now. Watch this space.
