### ISSUE TITLE
A favicon?

### ISSUE THREAD

**Issue by math2001** [jbt/markdown-editor#68]
hello!

First, thanks for this markdown editor, it's really cool. 👍 

I've got a problem, though. Here's how I store my bookmarks:

![image](https://cloud.githubusercontent.com/assets/15224242/23155154/7aa26c4e-f865-11e6-9f01-23050f355cb5.png)

So, as you can see, this looks quite bad... 

Do you have any plan on adding a favicon? What do you think of this:

![method-draw-image 2 1](https://cloud.githubusercontent.com/assets/15224242/23156031/673043e4-f869-11e6-90ad-83b27a5453ac.png)

(I have the `svg` version if you want)

Here's how it looks on a tab (chrome)

![image](https://cloud.githubusercontent.com/assets/15224242/23156095/b1599880-f869-11e6-9e3a-a53b7c555cb9.png)

Matt

PS: I manage to add it myself (with the `User JavaScript and CSS` extension), I just thought it'd be nice to share.

**Comment by aero31aero** [comment]
@math2001 Please create a PR for this, I am searching for a favicon myself and this seems nice. If possible, send PR to [this fork](https://github.com/aero31aero/markdown-editor) as well.
