### ISSUE TITLE
Codemirror version

### ISSUE THREAD

**Issue by radaniba** [jbt/markdown-editor#7]
I think markdown-editor is not working with current versions of Codemirror. I tested with 3.11 and 3.16 and the editor is totally broken, is there any plan to update to a more recent version of Codemirror ?

Thanks

**Comment by jbt** [comment]
Wow I've been terrible at maintaining this and replying to issues. I've bumped the codemirror version all the way to latest now and fixed the various api change issues that were breaking it.

In other news, at some point I am planning on completely swapping out codemirror for a completely different editor which is much less quirky with various bits of markdown syntax
