### ISSUE TITLE
Feature Request: Keyboard Shortcut

### ISSUE THREAD

**Issue by tovic** [jbt/markdown-editor#71]
That can be expanded from this:

https://gist.github.com/tovic/f1f21602e6b682ad78d6140f505e14f3

**Comment by aero31aero** [comment]
LGTM. Would try to add to my fork. :D

**Comment by aero31aero** [comment]
Merged as https://github.com/aero31aero/markdown-editor/commit/271653d44863552a68e71f3fc4f6826b1de0eed2 on rohitt.me/markdown-editor
Thanks @tovic !

**Comment by aero31aero** [comment]
Closing this. Please refer to #77.
