### ISSUE TITLE
<kbd> is not supported

### ISSUE THREAD

**Issue by optozorax** [jbt/markdown-editor#73]
GitHub markdown supports it and styling it in round-rect. It means keyboard key.

Example of usage `<kbd>`:

Press <kbd>Ctrl</kbd>+<kbd>F10</kbd> to Compile.
`Press <kbd>Ctrl</kbd>+<kbd>F10</kbd> to Compile.`

**Comment by aero31aero** [comment]
This has been fixed in a PR yet to be merged. Just in case you want, I've merged that specific patch in my fork hosted on http://rohitt.me/markdown-editor

**Comment by aero31aero** [comment]
Closing this. Please refer to #77.
