### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by jbt** [jbt/markdown-editor#74]
As mentioned in #61 and a couple of other places, I've been doing an absolutely terrible job (i.e. completely failing) at giving this project the time and love it deserves.

To that end, I'm more than happy to hand control over to someone else / a group of collabs who can do a much better job than me.

@aero31aero has volunteered over in #61, but I know there are others with active forks and who may be interested in taking this on - and I don't want to simply hand over the keys to the first person to actually ask.

So anyone who wants to be added as a collab, let everyone know here. And if there's no disagreement, after enough time that nobody's been unfairly missed out (I'm thinking a day or two), I'll add collab(s) - I'm happy to add several people, so long as they're happy to work together.

**Comment by smileytechguy** [comment]
I would like to work on this project some, I use it a lot, and am happy to help.

**Comment by jbt** [comment]
Well, as they say - the easiest way to make several weeks go by is to say you'll come back to something in a day or two on an open source project. Sorry about that.

I honestly thought there'd be a couple more interested people here - @aero31aero are you still interested here?

@smileytechguy I'm a little reluctant to hand it straight over to you, simply on the grounds that I haven't seen any previous activity / work on a fork from you (please correct me if I'm being a bit slow and missing something); meanwhile I know there've been others working more visibly on contributing + improving their own forks etc to make up for my lack of love over here. That said, if none of those folk are interested then I'm happy to let you give it a shot.

Since a vague "day or two" turned out to be a silly thing for me to hold myself to, I'm going to set a date: **July 1st**. Anyone interested please make yourself known before then.

**Comment by smileytechguy** [comment]
@jbt I very much understand, and feel you should give it to the most active person here, which is certainly not me

**Comment by aero31aero** [comment]
@jbt yes I'm still interested.

**Comment by jbt** [comment]
Well, it's July 1st! @aero31aero I just invited you as a collab. Go for it!
