### ISSUE TITLE
The buttons in the title bar are broken in Microsoft Edge

### ISSUE THREAD

**Issue by Lazerbeak12345** [jbt/markdown-editor#80]
(_In Microsoft Edge, with a 1366*768px screen, with the window maximized_) The text and icons in the buttons in the title bar (excluding the text "# Markdown Editor") don't show up.

Additionally the buttons are wider than they should be, and one of them wraps across and covers content.

**Comment by izhizheng** [comment]
1. download [Material Icons 3.0.1](https://github.com/google/material-design-icons/releases/download/3.0.1/material-design-icons-3.0.1.zip)
2. copy the following files to the markdown-editor/lib dir
    material-design-icons-3.0.1/iconfont/material-icons.css
    material-design-icons-3.0.1/iconfont/MaterialIcons-Regular.eot
    material-design-icons-3.0.1/iconfont/MaterialIcons-Regular.ijmap
    material-design-icons-3.0.1/iconfont/MaterialIcons-Regular.svg
    material-design-icons-3.0.1/iconfont/MaterialIcons-Regular.ttf
    material-design-icons-3.0.1/iconfont/MaterialIcons-Regular.woff
    material-design-icons-3.0.1/iconfont/MaterialIcons-Regular.woff2

for reference only

**Comment by aero31aero** [comment]
Hey! I'm unable to reproduce this on my end. Can you share a screenshot of what the broken bar looks like?

**Comment by izhizheng** [comment]
1. Can't see the buttons
<img width="960" alt="2018-01-09_201204" src="https://user-images.githubusercontent.com/27559529/34720389-7de5d8de-f579-11e7-9213-09a7ef18b4a9.png">

2. Press Ctrl+A
<img width="960" alt="2018-01-09_200442" src="https://user-images.githubusercontent.com/27559529/34720413-94c6e3ae-f579-11e7-9c56-b813510fee33.png">

**Comment by aero31aero** [comment]
I'm helpless on this as I cannot get a test machine with Windows/Edge here. Does switching to Material Icons 3.0.1 fix this? Also, is there any relation between using woff2 format for the icons and the breakage?

Thanks for looking into this @izhizheng

**Comment by izhizheng** [comment]
In my environment, I found that adding "font-feature-settings: 'liga';" to lib/material-icons.css will solve this problem, nothing else.
<img width="798" alt="2018-01-10_103427" src="https://user-images.githubusercontent.com/27559529/34753260-efd9c306-f5f1-11e7-80c7-fd6bd81afa1d.png">
<img width="960" alt="2018-01-10_101548" src="https://user-images.githubusercontent.com/27559529/34752975-6136cf64-f5f0-11e7-9e7a-44fe67923211.png">
