### ISSUE TITLE
New version does not look like github's markdown preview for code blocks

### ISSUE THREAD

**Issue by ventz** [jbt/markdown-editor#83]
Hi,

For some reason the new version does not look like github's preview (at least under Chrome).
(Specifically around code blocks)

The older version was a perfect clone of github's markdown "preview".

**Comment by aero31aero** [comment]
Hey! Can you please show some screenshots of the issue? That'd be really helpful in debugging this.

**Comment by ventz** [comment]
![image](https://user-images.githubusercontent.com/901168/36122657-2835052c-1018-11e8-846e-c8e9d1fa02a2.png)

**Comment by ventz** [comment]
Here is what it looks like on github:

![image](https://user-images.githubusercontent.com/901168/36123040-71c307d8-1019-11e8-95e6-6f98942fccbb.png)

**Comment by aero31aero** [comment]
I'm sorry I don't understand the difference. Are you talking of color scheme? Or is there some rendering issue I'm missing here.

 The only change I notice is the background color being non-white, and that was for easing the contrast. I could undo that for a pure github experience, however.

**Comment by ventz** [comment]
Yea, I think it's just the color scheme -- the color bleed makes it so that the blocks don't stand out, and it "bleeds" into the background. At first I thought it wasn't placing the blocks at all -- but after looking at the screenshot, funny enough you can see the difference there.

If possible to get the background to be white and the color blocks to match the github "grey color" (RGB xF6F8FA I think?)

**Comment by aero31aero** [comment]
Fixed this. Thanks for reporting @ventz :tada:

**Comment by ventz** [comment]
@aero31aero - you are awesome! Thank you (and thanks for the quick fix!!)

Would you mind adding one more small color fix?
(for the HR line when you use the ```#``` or ```##``` or ```###```, etc)

From what I can tell, that's the only other item that doesn't show up well. Everything else shows up incredibly well.

By the way - your markdown preview is the only one that is easy/instant, and actually looks like github!!

**Comment by aero31aero** [comment]
Fixed that and some other similar colors in 3c1ee34 and deployed. Also, thanks! I've just recently begun maintaining and @jbt is the one who did all the initial hard work. :D
