### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by GloverDonovan** [jbt/markdown-editor#84]
Hello,

Can markdown-editor be licensed under a different license? (Technically you'd also need approval from everyone that made a non-trivial contribution since they retain the copyright to their original work).

See: https://opensource.google.com/docs/thirdparty/licenses/#wtfpl-not-allowed

Thanks

**Comment by waldyrious** [comment]
In case it helps, if the WTFPL-style public domain-like dedication is to be preserved, choosealicense.com [recommends the Unlicense](https://choosealicense.com/licenses/#unlicense) for this effect.

**Comment by jbt** [comment]
Happy to let @aero31aero make the call on this as the project's current maintainer, but as the original author I'm happy for this to be licensed in whatever way makes the most sense, ideally as open as possible (in retrospect it was remiss of me not to put a proper license in from the get-go)

**Comment by aero31aero** [comment]
Thanks for raising this @GloverDonovan! I'm thinking of the [MIT License](https://choosealicense.com/licenses/mit/). It is similar to WTFPL style for the usage(permissive), but preserves the original copyright. That restriction ideally prevents someone from copying and relicensing under another license.

**Comment by waldyrious** [comment]
[MIT](https://choosealicense.com/licenses/mit/) is fine, although I'm personally partial to the equivalent (but even simpler) [ISC license](https://choosealicense.com/licenses/isc/) :)

**Comment by GloverDonovan** [comment]
Sounds good to me. Let's make this happen!

**Comment by aero31aero** [comment]
Since its functionally equivalent, I'll go with ISC here then.
