### ISSUE TITLE
FR: permalink to view with reading mode disabled

### ISSUE THREAD

**Issue by aspiers** [jbt/markdown-editor#86]
A while ago I wrote [a page explaining gotchas with Markdown lists](https://jbt.github.io/markdown-editor/#zVU9b9swEN31K25LG9gyEGTKEqRD0aBoOzRLUXSgpLPFhOK5/LDif99HUracwAUKdMliA9Td47t77473ljZs2SmzoOi13dD1shUTB0vadmyDJ+0p9ExerdkHajgsCIEt41SFC08j/lJE9VOc3mirDH1R7qmT0ZLfcvvrXR/C1t+sVp1yuGGtHTfKmNpyWG2dPHIb/GqYUlZ+b4N6fl+1COGO1uJuqmpJRIqQCQY68FBVOKA72iqnNk5te9roXWI/iGPqOChtPKlGYqaWc2qih14nvmI458/ZOC7lcrcgK4Eeoy+Z5U6jLdc5Z6LiuRXbveAyHf0rpROE/2c2sQq9dqekfrBf0F4itSrpHEiNak+jDj2JNfsJOZF8CUiyzidHGpUC1XR7OnXwASh/yIXobJBLx5Brf0moaV18NPZsEaq6A7wVu3SMGx131ewQia5lWEpoa1h5tErsRSDeIb0TFIPq7pPPLuGVRjXpFmUQ/u0zBcmkShl/qcFoH7KD3ox/3p577qiJmLbSGwDpticflMP0Z7MoGqIJepn7OqO3Eg0oS0gmSvpXEfpdvVogufnFLJDUx8bz75j0OgLhloyUZe3VjpOw56AWKC85MSMlX7uYviE6OImNgVDrfD6q5Ae4x7Ymdgym+GmMtE+lIm1zEwCX7JHLBk+i3L6HydTqJG1qSifskzvTLB28jCjnsMMwTw23KvHW8GuGmt2JOLYSN/1kA6JPMtKg7P64aOH2EWPCCAX1An+O+Uz5trhnoiwQ50Rwui7mKS1MnwG7PYzF1anMeX0XpASepxEl+nM1WhnrKbaiWdf8CqD7uQLwUyi9B/+Ed1s6u6SPxwFMNFIcoFNEqeO7DJCen8OhRURf0cDSt8OU40F4oUw9B5dJmj/B2P64/jxz2V7RsM8C7tjtTxaWpDctRQ/6mRqwn+0Hz1Wv38U68aV7tKiVYUCfyko9/4jWfwA=).  The main value of this page is gained when seeing the raw Markdown side-by-side with the rendered version.  The above link used to show that, but now the Editor defaults to reading mode, so it's no longer useful.

I presume there was some good reason for changing the default view, but it doesn't work for this particular use case, so please can there be a way to permalink to content with reading mode disabled?

**Comment by aero31aero** [comment]
The reason was that some people were using this to write some text, and then use a url shortner to share the link with others primarily for viewing.

I had been thinking of having this controlled via query params, so the url would become something like:

https://jbt.github.io/markdown-editor?read=false&dark=true#68aV7tKiVYUCfyko9/4jWfwA=

Thanks for reporting this.

**Comment by aspiers** [comment]
Yes, something like that would be perfect.  Thanks a lot for the quick reply!!

**Comment by aero31aero** [comment]
You should be able to use this like `.../?reading=false#...`. I'll add the UI for this later, but this should solve your purpose.

**Comment by aero31aero** [comment]
Sort of... As in, I know why it's doing that and that it needs fixing, but
I had some urgent college work to get to so I thought I'll fix that (and
remove a bunch of logging statements) while figuring out a UI for this.

**Comment by aspiers** [comment]
Ok just checking 😉
