### ISSUE TITLE
Support of 'mermaid' graph

### ISSUE THREAD

**Issue by ankurloriya** [jbt/markdown-editor#90]
Hello,

I am suggesting a feature which provides more value to your tool. there is messing feature kind of graph.
Gitlab provides markdown with 3rd party graph. https://mermaidjs.github.io/

**Comment by aero31aero** [comment]
Hey! This sounds interesting. However, the scope of this project is to be a simple editor compatible with the GitHub implementation of markdown, and thus it wouldn't be *expected* behavior to have this feature.

Thanks for the suggestion, however. If you feel like there can be a separate mode for GitLab compatability/enabling other features, I would be happy to merge your PRs. :)

**Comment by gorban** [comment]
Should this be reopened considering GitHub supports rendering MermaidJS from Markdown now?\
<https://github.blog/developer-skills/github/include-diagrams-markdown-files-mermaid/#enter-mermaid-%f0%9f%a7%9c%e2%99%80%ef%b8%8f%f0%9f%a7%9c%e2%99%82%ef%b8%8f>
