### ISSUE TITLE
Disable backspace when editor not focused

### ISSUE THREAD

**Issue by SixWays** [jbt/markdown-editor#95]
It's my own fault for not saving somewhere else, but I just lost about 45 minutes of work by pressing backspace while the reader was focused (thereby triggering "back"). It would be... preferable if this didn't happen.

**Comment by aero31aero** [comment]
@SixWays check if the new fix works for you. I ended up covering other cases than actually pressing backspace as well, but this *might* be sort of intrusive if you accidentally keep pressing the back button repeatedly by accident.
