### ISSUE TITLE
Cannot disable spell checking?

### ISSUE THREAD

**Issue by iago-lito** [jbt/markdown-editor#96]
I guess it's related to [this post](https://github.com/jbt/markdown-editor/issues/38#issuecomment-424627651) in #38 that hasn't lead to the opening of a new issue yet. I can see no option to disable the spelch.. skellpech.. the checkspeller.. which is annoying if we use custom words or non-english languages:

![spellchecker](https://user-images.githubusercontent.com/10091387/47361994-a802cf00-d6d3-11e8-9c04-966f165178be.png)

How do I disable it?

This is it. Thank you for support anyway. This online editor is a nugget :)

**Comment by aero31aero** [comment]
Hey, it's a pretty easy fix, I'm thinking of doing it soon but I got busy
with college. I'll try to get on this in the next couple of days.

I'm thinking of making this another toggle button on top.

**Comment by aero31aero** [comment]
@iago-lito check it out and tell if the fix works fine for you. I've got saving the preferences in the browser on the map as well so you don't have to always keep toggling them but that'd be a slightly larger refactor.

**Comment by iago-lito** [comment]
Wow, nice ^ ^
Well, the button is there, but the checker seems always disabled no matter how much I click it. Also, I now get a firefox 

    This page is asking you to confirm that you want to leave -
    data you have entered may not be saved.

popup message whenever I try to leave the page.  
Does it work fine on your side ?

**Comment by aero31aero** [comment]
There seems to be a bug on the side of the spellchecker in that it only computes the spellcheck on a keystroke. So, after a reload to the page, unless I type something, I don't see the spellcheck errors. Making any changes to the text fixes that.

About the second point, see #95. I'm pushing a commit to make those warnings less intrusive.

**Comment by iago-lito** [comment]
Everything fixed. Cheers, thank you :) And keep up with the good work! I find this website really neat and I regret it's not used more often by my colleagues :)
